### ISSUE TITLE
Paper 1.21 error

### ISSUE THREAD

**Issue by kveion** [DerFrZocker/Custom-Ore-Generator#37]
[03:51:15 INFO]: [custom-ore-generator] Enabling custom-ore-generator v2024.06.16

[03:51:15 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static de.derfrzocker.custom.ore.generator.impl.OreConfigYamlImpl de.derfrzocker.custom.ore.generator.impl.OreConfigYamlImpl.deserialize(java.util.Map)' of class de.derfrzocker.custom.ore.generator.impl.OreConfigYamlImpl for deserialization

java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.PUFF

at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]

at org.bukkit.Material.valueOf(Material.java:130) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.OreConfigYamlImpl.lambda$deserialize$2(OreConfigYamlImpl.java:177) ~[custom-ore-generator-2024.06.16.jar:?]

at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.OreConfigYamlImpl.deserialize(OreConfigYamlImpl.java:177) ~[custom-ore-generator-2024.06.16.jar:?]

at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]

at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]

at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]

at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.utils.Config.load(Config.java:89) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.utils.Config.<init>(Config.java:47) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.LazyOreConfigCache.getOreConfig(LazyOreConfigCache.java:109) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.OreConfigYamlDao.lambda$getAll$0(OreConfigYamlDao.java:107) ~[custom-ore-generator-2024.06.16.jar:?]

at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.OreConfigYamlDao.getAll(OreConfigYamlDao.java:107) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.CustomOreGeneratorServiceImpl.getOreConfigs(CustomOreGeneratorServiceImpl.java:239) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.CustomOreGenerator.onEnable(CustomOreGenerator.java:209) ~[custom-ore-generator-2024.06.16.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-129-4d7cef3]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-129-4d7cef3]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-129-4d7cef3]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-129-4d7cef3]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[03:51:15 ERROR]: Error occurred while enabling custom-ore-generator v2024.06.16 (Is it up to date?)

java.lang.RuntimeException: File plugins/custom-ore-generator/data/ore-config/ruby.yml does not have a OreConfig under the key 'value'

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.LazyOreConfigCache.getOreConfig(LazyOreConfigCache.java:114) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.OreConfigYamlDao.lambda$getAll$0(OreConfigYamlDao.java:107) ~[custom-ore-generator-2024.06.16.jar:?]

at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.dao.OreConfigYamlDao.getAll(OreConfigYamlDao.java:107) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.impl.CustomOreGeneratorServiceImpl.getOreConfigs(CustomOreGeneratorServiceImpl.java:239) ~[custom-ore-generator-2024.06.16.jar:?]

at custom-ore-generator-2024.06.16.jar/de.derfrzocker.custom.ore.generator.CustomOreGenerator.onEnable(CustomOreGenerator.java:209) ~[custom-ore-generator-2024.06.16.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-129-4d7cef3]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-129-4d7cef3]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-129-4d7cef3]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-129-4d7cef3]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-129-4d7cef3]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[03:51:15 INFO]: [custom-ore-generator] Disabling custom-ore-generator v2024.06.16

**Comment by kveion** [comment]
Ore config:

`# Only edit this file if you 10000% sure you know what you are doing. 
# You can set everything via the plugin commands, no need to edit this file manully.

value:
  ==: CustomOreGenerator#OreConfig
  name: ruby
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: true
  replace-materials:
  - DEEPSLATE
  - PUFF
  custom-data:
    ORAXEN: ruby_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 150.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      HEIGHT_RANGE: 20.0
      VEINS_PER_CHUNK: 1.0
      MINIMUM_HEIGHT: 26.0`

**Comment by kveion** [comment]
Ore config

`value:
  ==: CustomOreGenerator#OreConfig
  name: ruby
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: true
  replace-materials:
  - DEEPSLATE
  - PUFF
  custom-data:
    ORAXEN: ruby_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 150.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      HEIGHT_RANGE: 20.0
      VEINS_PER_CHUNK: 1.0
      MINIMUM_HEIGHT: 26.0`

**Comment by DerFrZocker** [comment]
In `replace-materials`, there is no Material / Block in Minecraft with the name `PUFF` did you mean `TUFF`?

**Comment by kveion** [comment]
uh my issue thanks, maybe you shoud add warns in console?
