### ISSUE TITLE
Update please to 1.18.2

### ISSUE THREAD

**Issue by Soupborsh** [DerFrZocker/Custom-Ore-Generator#4]
[16:26:41] [Server thread/INFO]: [custom-ore-generator] Loading custom-ore-generator v2021.12.5
[16:26:41] [Server thread/WARN]: [custom-ore-generator] The Server version which you are running is unsupported, you are running version 'UNKNOWN'
[16:26:41] [Server thread/WARN]: [custom-ore-generator] The plugin supports following versions 'v1_8_R1' 'v1_8_R2' 'v1_8_R3' 'v1_9_R1' 'v1_9_R2' 'v1_10_R1' 'v1_11_R1' 'v1_12_R1' 'v1_13_R1' 'v1_13_R2' 'v1_14_R1' 'v1_15_R1' 'v1_16_R1' 'v1_16_R2' 'v1_16_R3' 'v1_17_R1' 'v1_18_R1'
[16:26:41] [Server thread/WARN]: [custom-ore-generator] (Spigot / Paper version 1.8 - 1.18), if you are running such a Minecraft version, than your bukkit implementation is unsupported, in this case please contact the developer, so he can resolve this Issue
[16:26:41] [Server thread/WARN]: [custom-ore-generator] The Version 'UNKNOWN' can indicate, that you are using a newer Minecraft version than currently supported.
[16:26:41] [Server thread/WARN]: [custom-ore-generator] In this case please update to the newest version of this plugin. If this is the newest Version, than please be patient. It can take some weeks until the plugin is updated
[16:26:41] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[16:26:41] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[16:26:41] [Server thread/INFO]: [custom-ore-generator] Enabling custom-ore-generator v2021.12.5
[16:26:41] [Server thread/WARN]: [custom-ore-generator] No compatible Server version found!
java.lang.IllegalStateException: No compatible Server version found!
	at de.derfrzocker.custom.ore.generator.CustomOreGenerator.onEnable(CustomOreGenerator.java:175) ~[custom-ore-generator-2021.12.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:26:41] [Server thread/INFO]: [custom-ore-generator] Disabling custom-ore-generator v2021.12.5

**Comment by Soupborsh** [comment]
I'm also using Oraxen
